name: CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run unit tests
        run: poetry run pytest --maxfail=1 --disable-warnings

  integration:
    runs-on: ubuntu-latest
    needs: test
    env:
      KALI_INTEGRATION: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - uses: docker/setup-buildx-action@v3
      - name: Build test image (loaded locally)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/kali-mcp-server:test-${{ github.sha }}
      - name: Run integration tests
        env:
          KALI_TEST_IMAGE: ghcr.io/${{ github.repository_owner }}/kali-mcp-server:test-${{ github.sha }}
        run: poetry run pytest tests/integration/test_run_tool_container.py

  publish-ghcr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/kali-mcp-server
          tags: |
            type=raw,value=latest
            type=sha
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
